version: "3.2"

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
    
services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    ports:
      - 9200:9200
    labels:
      - traefik.enable=true
      - traefik.backend=elasticsearch
      - traefik.frontend.rule=Host:elasticsearch
      - traefik.port=9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.ml.enabled=true
      - xpack.graph.enabled=true

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.5.2
    ports:
      - 5601:5601
    volumes:
      - kibana_data:/usr/share/kibana/data
    labels:  # used for Traefik dynamic configuration
      - traefik.enable=true
      - traefik.backend=kibana
      - traefik.frontend.rule=Host:kibana
      - traefik.port=5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.security.enabled=false
