version: "3"
services:
    web:
      image: nginx:latest
      ports:
        - "8081:80"
      volumes:
        - ./www:/usr/share/nginx/html
        - ./default.conf:/etc/nginx/conf.d/default.conf
      links:
        - php

    php:
      image: php:7-fpm-alpine
      volumes: 
        - ./www:/usr/share/nginx/html
      links:
        - mysql

    mysql:
      image: mysql:latest
      ports:
        - "3306:3306"
      environment: 
        - MYSQL_ROOT_PASSWORD=password

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:db
      ports:
        - "8082:80"
      environment:
        - PMA_USER=root
        - PMA_PASSWORD=password
        - PHP_UPLOAD_MAX_FILESIZE=100MB